version: '2.1'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=drf_apm
      - MYSQL_USER=drf_apm
      - MYSQL_PASSWORD=drfapmtest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      elasticsearch: 
        condition: service_healthy

  apm_server:
    image: docker.elastic.co/apm/apm-server:6.2.4
    ports:
      - 8200:8200
    volumes:
      - ./files/apm-server.yml:/usr/share/apm-server/apm-server.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

  api:
    build: .
    links:
      - mysql
      - mysql:db
      - apm_server
      - apm_server:apmserver
    ports:
      - "8000:8000"
