"""
Django settings for drf_apm project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import better_exceptions
better_exceptions.MAX_LENGTH = None
from .base import *


INSTALLED_APPS += ('django_extensions',)
